### ISSUE TITLE
Recent commits generate an error.

### ISSUE THREAD

**Issue by wangfei800** [wizacha/AwsSignatureMiddleware#6]
After I run command composer update, local lib was updated to 0.1.1, then I got error:

The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details .......

**Comment by vdechenaux** [comment]
Hi,

Oops :( Can you require `0.1.0` until we push a fix?

To reproduce the bug, what version of `elasticsearch/elasticsearch` are you using?
What's is the host / port ?

Thanks

**Comment by wangfei800** [comment]
Thank you, I force to use 0.1.0 to avoid this issue.

The elasticsearch/elasticsearch I am using is v2.3.2, which is the newest.

The host is amazon aws, the port is 443.

**Comment by vdechenaux** [comment]
https://github.com/wizacha/AwsSignatureMiddleware/releases/tag/v0.1.2 has been released. Thanks
